### ISSUE TITLE
rollback causes the server to endlessly restart when using nodemon

### ISSUE THREAD

**Issue by ksambhi** [ksambhi/jakhu#25]
This happens when NODE_ENV does not equal 'dev'

**Comment by ksambhi** [comment]
Fix idea: backup to ~/.web/<servername>/rollback/backup<date>

**Comment by ksambhi** [comment]
This might be fixed

**Comment by ksambhi** [comment]
Fixed - rollback -> ~/.jakhu

**Comment by Gum-Joe** [comment]
y
